#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
yarn check-format ||
(
    echo '🤢🤮🤢🤮 Its FOKING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
    ❌Prettier Check Failed.❌
    👉 Run npm run format,
    👉 Add changes and
    👉 Try commit again.';
    false;
)

# Check ESLint Standards
yarn check-lint ||
(
    echo '😤🏀👋😤 Get that weak shit out of here! 😤🏀👋😤
    ❌ESLint Check Failed.❌
    👉 Make the required changes listed above,
    👉 Add changes and
    👉 Try to commit again.'
    false;
)

# Check tsconfig standards
npm run check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
    Are you seriously trying to write that? Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
